### PR TITLE
sup kitty

### PR DESCRIPTION
**Pull request by paulczar**

### CODE REVIEW

**Comment by jjasghar** [comment]
Wow, that's fucked up.

**Comment by moutons** [comment]
NSFL 👎

**Comment by filler** [comment]
Im 👎  on the murdaaaa also.

**Review by moutons — CHANGES_REQUESTED** [review]
hey check it out this is a review since GH lets us do that now :partyparrot:

I think that this could run counter to the #hugops not harm clause, given that this is totes fucked in general. Given that view, I'm requesting the following changes: end racism and violence.

**Comment by paulczar** [comment]
so if I end racism and violence we can merge this as is ?

**Pull request closed without merging**
