### PR TITLE
CSS is a tire fire

### PR DESCRIPTION
**Pull request by rnelson0**

### CODE REVIEW

**Comment by onlyhavecans** [comment]
Please add the gif to the directory instead of linking off.
Also I love that so much

**Comment by rnelson0** [comment]
All good now!

**Comment by rnelson0** [comment]
Just curious, does the website take time to update, or is the /css endpoint a problem because it has 'real' contents?

**Comment by jjasghar** [comment]
it works for me 🤘 

http://tirefi.re/css/

**Comment by rnelson0** [comment]
lol I was viewing it through twitter iOS client (don't ask) which does crappy caching with no refresh ability. Twitter is a tire fire. Go figure!

**Pull request merged**
