### PR TITLE
Add support for previewing locally

### PR DESCRIPTION
**Pull request by filler**
Uses docker-compose to pull down pages-ready jekyll from Docker Hub.

Also lays down a Makefile with targets to lifecycle manage
docker-compose resources.

This lets you preview changes pre-commit so you dont commit 🚮!

### CODE REVIEW

**Comment by filler** [comment]
Can a couple more early Christians use this and kick the not-on-fire tires to make sure this twerks on your machine ops problem now?

THANKS

**Comment by filler** [comment]
OH!  Also this does a 💩 job of figuring out that jekyll is live on `tcp/4000` before kicking off the `open`.  I tried for a few but then gave up as I would end up having to inspect cURL responses.  Feel free to pick that twerk back up, devopses.

**Comment by jjasghar** [comment]
🍶

**Comment by moutons** [comment]
github

**Pull request merged**
