### PR TITLE
pete cheslock should have his own websight

### PR DESCRIPTION
**Pull request by paulczar**

### CODE REVIEW

**Comment by filler** [comment]
Seth and not Chesbot?

**Comment by paulczar** [comment]
yeah I thought linking to chesbot would be too obvious

**Comment by paulczar** [comment]
also wtf does that error mean

**Comment by moutons** [comment]
`404 No error` how hard is that to understand? :tire: :fire: :finedog:

**Comment by moutons** [comment]
if someone wants to figure out how to make liquid render the page links as internal/relative site links instead of hardlinks that'll get fixed, it's in /about/index.md

maybe I'm wrong, that error seems to be coming from the page itself

**Pull request merged**
