### PR TITLE
gotta send this out...but not outside.

### PR DESCRIPTION
**Pull request by jjasghar**

### CODE REVIEW

**Comment by jjasghar** [comment]
There was a tweet with city workers painting "2 meters" between each person, I couldn't find in though :(

**Comment by jjasghar** [comment]
Maybe add a _count_ _up_ on how long we've been quarantined?

**Comment by onlyhavecans** [comment]
I have so many "use protection I can't afford to go to 27 baby showers in December" and "The QuarenTeens" meme's right nows. I like it

**Comment by moutons** [comment]
Why isn't this merged yet?

**Pull request merged**
