### PR TITLE
IT\'S THE YEAR OF CHESLOCK ON THE DESKTOP

### PR DESCRIPTION
**Pull request by gwaldo**

### CODE REVIEW

**Comment by filler** [comment]
`s/_/-/` in your paths, and youre on fire! :fire:

**Comment by jjasghar** [comment]
Oh! And a download link so you can have it on your desktop too!

**Comment by gwaldo** [comment]
Ok, @moutons @filler @jjasghar, have a look.

* Renamed file paths
* Added link to get your very own desktop background!
* Took a stab at making it the background image of the Pete Shrine.  I don't know whether it will work; might depend on what's doing the render/conversion.

**Comment by jjasghar** [comment]
🤘

**Comment by filler** [comment]
:-1: u made it awful lmao

image

great now i hate pete

**Comment by gwaldo** [comment]
How's that, @filler?  Am I beautiful now?

**Comment by filler** [comment]
:cool: 😎 💯 

However your going to fail tests and not work with a local build given the absolute URL!  :trollface:

**Comment by gwaldo** [comment]
Those comments helped, @filler.  Thanks!

**Comment by filler** [comment]
Tight.  Marge away!

**Comment by gwaldo** [comment]
🙌

**Pull request merged**
