### PR TITLE
Added OpenStack because OpenStack

### PR DESCRIPTION
**Pull request by jjasghar**

### CODE REVIEW

**Comment by jjasghar** [comment]
I was also thinking: 

image

**Comment by moutons** [comment]
It's hard for me not to vote for http://cube-drone.com/comics/c/alien-geometries

alien geometries

**Comment by moutons** [comment]
because @classam is 💯

**Comment by jjasghar** [comment]
so I thought about that, but it's already at http://lolpenstack.org/ felt like we needed something original. We can link to it right?

**Comment by cube-drone** [comment]
Yup, all my stuff is creative commons

**Comment by moutons** [comment]
well @jjasghar I'd say that's a resounding 👌 :shipit: with the link

**Pull request merged**
