### PR TITLE
Docker, no Moby, no Docker NO MOBY!

### PR DESCRIPTION
**Pull request by sntxrr**

### CODE REVIEW

**Comment by moutons** [comment]
So I had to do something silly in the liquid templating to make the redirects work when I switched the site to using jekyll. I can fix it with the dockermoby update, but I'm not going to be able to work on it tonight because sleep and stuff. You can see the liquid stuff here 
https://github.com/tirefire/tirefi.re/blob/master/_includes/head.html#L6

**Comment by moutons** [comment]
I guess travis calls it good because htmlproofer doesn't know how to check the redirects in the header? That sounds like something I'm definitely not fixing sorry not sorry

**Comment by sntxrr** [comment]
I tickled a couple things to get the refreshes to work, thanks for that pointer.  Lemme know if it needs anything else before we ~~Docker~~ Moby up this tirefi.re!

**Review by paulczar — APPROVED** [review]
seems legit, lets publish this!

**Comment by moutons** [comment]
@paulczar the redirects were broken I don't want to push a 😿

**Comment by moutons** [comment]
I'm a monster. @rrxtns merge https://github.com/rrxtns/tirefi.re/pull/1 and I can merge this.

**Comment by sntxrr** [comment]
@moutons it has been done.. tested local, tested in CI, and a touch of documentation for the next tirefi.re PR submission.

**Comment by moutons** [comment]
sorry about the delay I got allergic to the computer for a while there

**Pull request merged**
