### PR TITLE
Add travis notifications to Slack

### PR DESCRIPTION
**Pull request by moutons**

### CODE REVIEW

**Comment by jjasghar** [comment]
Is that encrypted? ;)

**Comment by jjasghar** [comment]
you know you love me.

**Comment by moutons** [comment]
yes I invalidated the old token sorry mr Director

**Comment by jjasghar** [comment]
Good to see you do the [DevOps||Needful].

**Comment by moutons** [comment]
don't we have a slack for this? ;)

**Comment by jjasghar** [comment]
touche'

**Pull request merged**
