### PR TITLE
openstack is not a firefire

### PR DESCRIPTION
**Pull request by paulczar**
luuulz i should have checked first ...  there's already a PR for openstack.   oh well, we can fight about it.

### CODE REVIEW

**Comment by jjasghar** [comment]
I feel like we should merge these two for great power: https://github.com/moutons/tirefi.re/pull/14

so that tweet, the scary real image, the lolpenstack.org link?

**Comment by jjasghar** [comment]
Rebase, and "Yes and" this!

**Comment by paulczar** [comment]
clicky clicky mergy mergy

**Comment by moutons** [comment]
@paulczar check your invites devop

**Pull request merged**
